baseURL = "/"
title   = "Sarvagya Sagar"

DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"
enableInlineShortcodes = true
rssLimit  = 50  

googleAnalytics = "UA-158716114-1"
disqusShortname = "0xdotexe-github-io"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true
comments     = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Sarvagya Sagar"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "0xdotexe :: Hack the hacker before hacker hacks you"
  keywords = "Sarvagya Sagar, Hack the hacker before hacker hacks you, 0xdotexe, OSINT, malware analysis, Cryptography"
  images = ["/logo.jpg"]

  homeSubtitle = "Hack the hacker before hacker hacks you"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/0xdotexe/blog.git"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = true  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "light"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
    logoText     = "root@heart : "
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/0xdotexe"

  [[params.social]]
    name = "email"
    url  = "mailto:ssomsec@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/0xdotexe"

  [[params.social]]
    name = "facebook"
    url  = "https://www.facebook.com/0xdotexe"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/0xdotexe"
  [[params.social]]
    name = "gitlab"
    url ="https://gitlab.com/0xdotexe"
  [[params.social]]
    name = "keybase"
    url ="https://keybase.io/0xdotexe"

[languages]
  [languages.en]
    subtitle  = "Welcome"
    weight    = 1

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
